name: Run bazel build
on:
  push:
    branches: [ main ]

jobs:
  bazel-build:
    name: Bazel build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          bazel build //...

      - name: test
        run: |
          bazel test //...
    
      - name: benchmark
        run: |
          bazel run --config profile //lib/myers:benchmark
